/**********************************************************************
 * Extern for Swipeout
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Swipeout = {
  "defaultProps": {
    "autoClose": {},
    "disabled": {},
    "left": {},
    "onClose": function () {},
    "onOpen": function () {},
    "prefixCls": {},
    "right": {}
  }
};
Swipeout.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for Swipeout
/**********************************************************************/
